from collections import OrderedDict


ASSISTANCE_BROKER_USASPENDING_MAP = OrderedDict(
    [
        ("created_at", "created_at"),
        ("updated_at", "updated_at"),
        ("action_date", "action_date"),
        ("action_type", "action_type"),
        ("assistance_type", "assistance_type"),
        ("award_description", "award_description"),
        ("awardee_or_recipient_legal", "awardee_or_recipient_legal"),
        ("awardee_or_recipient_uniqu", "awardee_or_recipient_uniqu"),
        ("awarding_agency_code", "awarding_agency_code"),
        ("awarding_office_code", "awarding_office_code"),
        ("awarding_sub_tier_agency_c", "awarding_sub_tier_agency_c"),
        ("award_modification_amendme", "award_modification_amendme"),
        ("business_funds_indicator", "business_funds_indicator"),
        ("business_types", "business_types"),
        ("cfda_number", "cfda_number"),
        ("correction_delete_indicatr", "correction_delete_indicatr"),
        ("face_value_loan_guarantee", "face_value_loan_guarantee"),
        ("fain", "fain"),
        ("federal_action_obligation", "federal_action_obligation"),
        ("fiscal_year_and_quarter_co", "fiscal_year_and_quarter_co"),
        ("funding_agency_code", "funding_agency_code"),
        ("funding_office_code", "funding_office_code"),
        ("funding_sub_tier_agency_co", "funding_sub_tier_agency_co"),
        ("legal_entity_address_line1", "legal_entity_address_line1"),
        ("legal_entity_address_line2", "legal_entity_address_line2"),
        ("legal_entity_address_line3", "legal_entity_address_line3"),
        ("legal_entity_country_code", "legal_entity_country_code"),
        ("legal_entity_foreign_city", "legal_entity_foreign_city"),
        ("legal_entity_foreign_posta", "legal_entity_foreign_posta"),
        ("legal_entity_foreign_provi", "legal_entity_foreign_provi"),
        ("legal_entity_zip5", "legal_entity_zip5"),
        ("legal_entity_zip_last4", "legal_entity_zip_last4"),
        ("non_federal_funding_amount", "non_federal_funding_amount"),
        ("original_loan_subsidy_cost", "original_loan_subsidy_cost"),
        ("period_of_performance_curr", "period_of_performance_curr"),
        ("period_of_performance_star", "period_of_performance_star"),
        ("place_of_performance_code", "place_of_performance_code"),
        ("place_of_performance_congr", "place_of_performance_congr"),
        ("place_of_perform_country_c", "place_of_perform_country_c"),
        ("place_of_performance_forei", "place_of_performance_forei"),
        ("place_of_performance_zip4a", "place_of_performance_zip4a"),
        ("record_type", "record_type"),
        ("sai_number", "sai_number"),
        ("uri", "uri"),
        ("legal_entity_congressional", "legal_entity_congressional"),
        ("total_funding_amount", "total_funding_amount"),
        ("cfda_title", "cfda_title"),
        ("awarding_agency_name", "awarding_agency_name"),
        ("awarding_sub_tier_agency_n", "awarding_sub_tier_agency_n"),
        ("funding_agency_name", "funding_agency_name"),
        ("funding_sub_tier_agency_na", "funding_sub_tier_agency_na"),
        ("is_historical", "is_historical"),
        ("place_of_perform_county_na", "place_of_perform_county_na"),
        ("place_of_perform_state_nam", "place_of_perform_state_nam"),
        ("place_of_performance_city", "place_of_performance_city"),
        ("legal_entity_city_name", "legal_entity_city_name"),
        ("legal_entity_county_code", "legal_entity_county_code"),
        ("legal_entity_county_name", "legal_entity_county_name"),
        ("legal_entity_state_code", "legal_entity_state_code"),
        ("legal_entity_state_name", "legal_entity_state_name"),
        ("modified_at", "modified_at"),
        ("afa_generated_unique", "afa_generated_unique"),
        ("is_active", "is_active"),
        ("awarding_office_name", "awarding_office_name"),
        ("funding_office_name", "funding_office_name"),
        ("legal_entity_city_code", "legal_entity_city_code"),
        ("legal_entity_foreign_descr", "legal_entity_foreign_descr"),
        ("legal_entity_country_name", "legal_entity_country_name"),
        ("place_of_perform_country_n", "place_of_perform_country_n"),
        ("place_of_perform_county_co", "place_of_perform_county_co"),
        ("submission_id", "submission_id"),
        ("place_of_perfor_state_code", "place_of_perfor_state_code"),
        ("place_of_performance_zip5", "place_of_performance_zip5"),
        ("place_of_perform_zip_last4", "place_of_perform_zip_last4"),
        ("action_type_description", "action_type_description"),
        ("assistance_type_desc", "assistance_type_desc"),
        ("business_funds_ind_desc", "business_funds_ind_desc"),
        ("business_types_desc", "business_types_desc"),
        ("correction_delete_ind_desc", "correction_delete_ind_desc"),
        ("record_type_description", "record_type_description"),
        ("ultimate_parent_legal_enti", "ultimate_parent_legal_enti"),
        ("ultimate_parent_unique_ide", "ultimate_parent_unique_ide"),
        ("unique_award_key", "unique_award_key"),
        ("high_comp_officer1_amount", "officer_1_amount"),
        ("high_comp_officer1_full_na", "officer_1_name"),
        ("high_comp_officer2_amount", "officer_2_amount"),
        ("high_comp_officer2_full_na", "officer_2_name"),
        ("high_comp_officer3_amount", "officer_3_amount"),
        ("high_comp_officer3_full_na", "officer_3_name"),
        ("high_comp_officer4_amount", "officer_4_amount"),
        ("high_comp_officer4_full_na", "officer_4_name"),
        ("high_comp_officer5_amount", "officer_5_amount"),
        ("high_comp_officer5_full_na", "officer_5_name"),
    ]
)

PROCUREMENT_BROKER_USASPENDING_MAP = OrderedDict(
    [
        ("created_at", "created_at"),
        ("updated_at", "updated_at"),
        ("piid", "piid"),
        ("detached_award_proc_unique", "detached_award_proc_unique"),
        ("agency_id", "agency_id"),
        ("awarding_sub_tier_agency_c", "awarding_sub_tier_agency_c"),
        ("awarding_sub_tier_agency_n", "awarding_sub_tier_agency_n"),
        ("awarding_agency_code", "awarding_agency_code"),
        ("awarding_agency_name", "awarding_agency_name"),
        ("parent_award_id", "parent_award_id"),
        ("award_modification_amendme", "award_modification_amendme"),
        ("type_of_contract_pricing", "type_of_contract_pricing"),
        ("type_of_contract_pric_desc", "type_of_contract_pric_desc"),
        ("contract_award_type", "contract_award_type"),
        ("contract_award_type_desc", "contract_award_type_desc"),
        ("naics", "naics"),
        ("naics_description", "naics_description"),
        ("awardee_or_recipient_uniqu", "awardee_or_recipient_uniqu"),
        ("ultimate_parent_legal_enti", "ultimate_parent_legal_enti"),
        ("ultimate_parent_unique_ide", "ultimate_parent_unique_ide"),
        ("award_description", "award_description"),
        ("place_of_performance_zip4a", "place_of_performance_zip4a"),
        ("place_of_perform_city_name", "place_of_perform_city_name"),
        ("place_of_perform_county_na", "place_of_perform_county_na"),
        ("place_of_performance_congr", "place_of_performance_congr"),
        ("awardee_or_recipient_legal", "awardee_or_recipient_legal"),
        ("legal_entity_city_name", "legal_entity_city_name"),
        ("legal_entity_state_code", "legal_entity_state_code"),
        ("legal_entity_state_descrip", "legal_entity_state_descrip"),
        ("legal_entity_zip4", "legal_entity_zip4"),
        ("legal_entity_congressional", "legal_entity_congressional"),
        ("legal_entity_address_line1", "legal_entity_address_line1"),
        ("legal_entity_address_line2", "legal_entity_address_line2"),
        ("legal_entity_address_line3", "legal_entity_address_line3"),
        ("legal_entity_country_code", "legal_entity_country_code"),
        ("legal_entity_country_name", "legal_entity_country_name"),
        ("period_of_performance_star", "period_of_performance_star"),
        ("period_of_performance_curr", "period_of_performance_curr"),
        ("period_of_perf_potential_e", "period_of_perf_potential_e"),
        ("ordering_period_end_date", "ordering_period_end_date"),
        ("action_date", "action_date"),
        ("action_type", "action_type"),
        ("action_type_description", "action_type_description"),
        ("federal_action_obligation", "federal_action_obligation"),
        ("current_total_value_award", "current_total_value_award"),
        ("potential_total_value_awar", "potential_total_value_awar"),
        ("funding_sub_tier_agency_co", "funding_sub_tier_agency_co"),
        ("funding_sub_tier_agency_na", "funding_sub_tier_agency_na"),
        ("funding_office_code", "funding_office_code"),
        ("funding_office_name", "funding_office_name"),
        ("awarding_office_code", "awarding_office_code"),
        ("awarding_office_name", "awarding_office_name"),
        ("referenced_idv_agency_iden", "referenced_idv_agency_iden"),
        ("referenced_idv_agency_desc", "referenced_idv_agency_desc"),
        ("funding_agency_code", "funding_agency_code"),
        ("funding_agency_name", "funding_agency_name"),
        ("place_of_performance_locat", "place_of_performance_locat"),
        ("place_of_performance_state", "place_of_performance_state"),
        ("place_of_perfor_state_desc", "place_of_perfor_state_desc"),
        ("place_of_perform_country_c", "place_of_perform_country_c"),
        ("place_of_perf_country_desc", "place_of_perf_country_desc"),
        ("idv_type", "idv_type"),
        ("idv_type_description", "idv_type_description"),
        ("referenced_idv_type", "referenced_idv_type"),
        ("referenced_idv_type_desc", "referenced_idv_type_desc"),
        ("vendor_doing_as_business_n", "vendor_doing_as_business_n"),
        ("vendor_phone_number", "vendor_phone_number"),
        ("vendor_fax_number", "vendor_fax_number"),
        ("multiple_or_single_award_i", "multiple_or_single_award_i"),
        ("multiple_or_single_aw_desc", "multiple_or_single_aw_desc"),
        ("referenced_mult_or_single", "referenced_mult_or_single"),
        ("referenced_mult_or_si_desc", "referenced_mult_or_si_desc"),
        ("type_of_idc", "type_of_idc"),
        ("type_of_idc_description", "type_of_idc_description"),
        ("a_76_fair_act_action", "a_76_fair_act_action"),
        ("a_76_fair_act_action_desc", "a_76_fair_act_action_desc"),
        ("dod_claimant_program_code", "dod_claimant_program_code"),
        ("dod_claimant_prog_cod_desc", "dod_claimant_prog_cod_desc"),
        ("clinger_cohen_act_planning", "clinger_cohen_act_planning"),
        ("clinger_cohen_act_pla_desc", "clinger_cohen_act_pla_desc"),
        ("commercial_item_acquisitio", "commercial_item_acquisitio"),
        ("commercial_item_acqui_desc", "commercial_item_acqui_desc"),
        ("commercial_item_test_progr", "commercial_item_test_progr"),
        ("commercial_item_test_desc", "commercial_item_test_desc"),
        ("consolidated_contract", "consolidated_contract"),
        ("consolidated_contract_desc", "consolidated_contract_desc"),
        ("contingency_humanitarian_o", "contingency_humanitarian_o"),
        ("contingency_humanitar_desc", "contingency_humanitar_desc"),
        ("contract_bundling", "contract_bundling"),
        ("contract_bundling_descrip", "contract_bundling_descrip"),
        ("contract_financing", "contract_financing"),
        ("contract_financing_descrip", "contract_financing_descrip"),
        ("contracting_officers_deter", "contracting_officers_deter"),
        ("contracting_officers_desc", "contracting_officers_desc"),
        ("cost_accounting_standards", "cost_accounting_standards"),
        ("cost_accounting_stand_desc", "cost_accounting_stand_desc"),
        ("cost_or_pricing_data", "cost_or_pricing_data"),
        ("cost_or_pricing_data_desc", "cost_or_pricing_data_desc"),
        ("country_of_product_or_serv", "country_of_product_or_serv"),
        ("country_of_product_or_desc", "country_of_product_or_desc"),
        ("construction_wage_rate_req", "construction_wage_rate_req"),
        ("construction_wage_rat_desc", "construction_wage_rat_desc"),
        ("evaluated_preference", "evaluated_preference"),
        ("evaluated_preference_desc", "evaluated_preference_desc"),
        ("extent_competed", "extent_competed"),
        ("extent_compete_description", "extent_compete_description"),
        ("fed_biz_opps", "fed_biz_opps"),
        ("fed_biz_opps_description", "fed_biz_opps_description"),
        ("foreign_funding", "foreign_funding"),
        ("foreign_funding_desc", "foreign_funding_desc"),
        ("government_furnished_prope", "government_furnished_prope"),
        ("government_furnished_desc", "government_furnished_desc"),
        ("information_technology_com", "information_technology_com"),
        ("information_technolog_desc", "information_technolog_desc"),
        ("interagency_contracting_au", "interagency_contracting_au"),
        ("interagency_contract_desc", "interagency_contract_desc"),
        ("local_area_set_aside", "local_area_set_aside"),
        ("local_area_set_aside_desc", "local_area_set_aside_desc"),
        ("major_program", "major_program"),
        ("purchase_card_as_payment_m", "purchase_card_as_payment_m"),
        ("purchase_card_as_paym_desc", "purchase_card_as_paym_desc"),
        ("multi_year_contract", "multi_year_contract"),
        ("multi_year_contract_desc", "multi_year_contract_desc"),
        ("national_interest_action", "national_interest_action"),
        ("national_interest_desc", "national_interest_desc"),
        ("number_of_actions", "number_of_actions"),
        ("number_of_offers_received", "number_of_offers_received"),
        ("other_statutory_authority", "other_statutory_authority"),
        ("performance_based_service", "performance_based_service"),
        ("performance_based_se_desc", "performance_based_se_desc"),
        ("place_of_manufacture", "place_of_manufacture"),
        ("place_of_manufacture_desc", "place_of_manufacture_desc"),
        ("price_evaluation_adjustmen", "price_evaluation_adjustmen"),
        ("product_or_service_code", "product_or_service_code"),
        ("product_or_service_co_desc", "product_or_service_co_desc"),
        ("program_acronym", "program_acronym"),
        ("other_than_full_and_open_c", "other_than_full_and_open_c"),
        ("other_than_full_and_o_desc", "other_than_full_and_o_desc"),
        ("recovered_materials_sustai", "recovered_materials_sustai"),
        ("recovered_materials_s_desc", "recovered_materials_s_desc"),
        ("research", "research"),
        ("research_description", "research_description"),
        ("sea_transportation", "sea_transportation"),
        ("sea_transportation_desc", "sea_transportation_desc"),
        ("labor_standards", "labor_standards"),
        ("labor_standards_descrip", "labor_standards_descrip"),
        ("small_business_competitive", "small_business_competitive"),
        ("solicitation_identifier", "solicitation_identifier"),
        ("solicitation_procedures", "solicitation_procedures"),
        ("solicitation_procedur_desc", "solicitation_procedur_desc"),
        ("fair_opportunity_limited_s", "fair_opportunity_limited_s"),
        ("fair_opportunity_limi_desc", "fair_opportunity_limi_desc"),
        ("subcontracting_plan", "subcontracting_plan"),
        ("subcontracting_plan_desc", "subcontracting_plan_desc"),
        ("program_system_or_equipmen", "program_system_or_equipmen"),
        ("program_system_or_equ_desc", "program_system_or_equ_desc"),
        ("type_set_aside", "type_set_aside"),
        ("type_set_aside_description", "type_set_aside_description"),
        ("epa_designated_product", "epa_designated_product"),
        ("epa_designated_produc_desc", "epa_designated_produc_desc"),
        ("materials_supplies_article", "materials_supplies_article"),
        ("materials_supplies_descrip", "materials_supplies_descrip"),
        ("transaction_number", "transaction_number"),
        ("sam_exception", "sam_exception"),
        ("sam_exception_description", "sam_exception_description"),
        ("city_local_government", "city_local_government"),
        ("county_local_government", "county_local_government"),
        ("inter_municipal_local_gove", "inter_municipal_local_gove"),
        ("local_government_owned", "local_government_owned"),
        ("municipality_local_governm", "municipality_local_governm"),
        ("school_district_local_gove", "school_district_local_gove"),
        ("township_local_government", "township_local_government"),
        ("us_state_government", "us_state_government"),
        ("us_federal_government", "us_federal_government"),
        ("federal_agency", "federal_agency"),
        ("federally_funded_research", "federally_funded_research"),
        ("us_tribal_government", "us_tribal_government"),
        ("foreign_government", "foreign_government"),
        ("community_developed_corpor", "community_developed_corpor"),
        ("labor_surplus_area_firm", "labor_surplus_area_firm"),
        ("corporate_entity_not_tax_e", "corporate_entity_not_tax_e"),
        ("corporate_entity_tax_exemp", "corporate_entity_tax_exemp"),
        ("partnership_or_limited_lia", "partnership_or_limited_lia"),
        ("sole_proprietorship", "sole_proprietorship"),
        ("small_agricultural_coopera", "small_agricultural_coopera"),
        ("international_organization", "international_organization"),
        ("us_government_entity", "us_government_entity"),
        ("emerging_small_business", "emerging_small_business"),
        ("c8a_program_participant", "c8a_program_participant"),
        ("sba_certified_8_a_joint_ve", "sba_certified_8_a_joint_ve"),
        ("dot_certified_disadvantage", "dot_certified_disadvantage"),
        ("self_certified_small_disad", "self_certified_small_disad"),
        ("historically_underutilized", "historically_underutilized"),
        ("small_disadvantaged_busine", "small_disadvantaged_busine"),
        ("the_ability_one_program", "the_ability_one_program"),
        ("historically_black_college", "historically_black_college"),
        ("c1862_land_grant_college", "c1862_land_grant_college"),
        ("c1890_land_grant_college", "c1890_land_grant_college"),
        ("c1994_land_grant_college", "c1994_land_grant_college"),
        ("minority_institution", "minority_institution"),
        ("private_university_or_coll", "private_university_or_coll"),
        ("school_of_forestry", "school_of_forestry"),
        ("state_controlled_instituti", "state_controlled_instituti"),
        ("tribal_college", "tribal_college"),
        ("veterinary_college", "veterinary_college"),
        ("educational_institution", "educational_institution"),
        ("alaskan_native_servicing_i", "alaskan_native_servicing_i"),
        ("community_development_corp", "community_development_corp"),
        ("native_hawaiian_servicing", "native_hawaiian_servicing"),
        ("domestic_shelter", "domestic_shelter"),
        ("manufacturer_of_goods", "manufacturer_of_goods"),
        ("hospital_flag", "hospital_flag"),
        ("veterinary_hospital", "veterinary_hospital"),
        ("hispanic_servicing_institu", "hispanic_servicing_institu"),
        ("foundation", "foundation"),
        ("woman_owned_business", "woman_owned_business"),
        ("minority_owned_business", "minority_owned_business"),
        ("women_owned_small_business", "women_owned_small_business"),
        ("economically_disadvantaged", "economically_disadvantaged"),
        ("joint_venture_women_owned", "joint_venture_women_owned"),
        ("joint_venture_economically", "joint_venture_economically"),
        ("veteran_owned_business", "veteran_owned_business"),
        ("service_disabled_veteran_o", "service_disabled_veteran_o"),
        ("contracts", "contracts"),
        ("grants", "grants"),
        ("receives_contracts_and_gra", "receives_contracts_and_gra"),
        ("airport_authority", "airport_authority"),
        ("council_of_governments", "council_of_governments"),
        ("housing_authorities_public", "housing_authorities_public"),
        ("interstate_entity", "interstate_entity"),
        ("planning_commission", "planning_commission"),
        ("port_authority", "port_authority"),
        ("transit_authority", "transit_authority"),
        ("subchapter_s_corporation", "subchapter_s_corporation"),
        ("limited_liability_corporat", "limited_liability_corporat"),
        ("foreign_owned_and_located", "foreign_owned_and_located"),
        ("american_indian_owned_busi", "american_indian_owned_busi"),
        ("alaskan_native_owned_corpo", "alaskan_native_owned_corpo"),
        ("indian_tribe_federally_rec", "indian_tribe_federally_rec"),
        ("native_hawaiian_owned_busi", "native_hawaiian_owned_busi"),
        ("tribally_owned_business", "tribally_owned_business"),
        ("asian_pacific_american_own", "asian_pacific_american_own"),
        ("black_american_owned_busin", "black_american_owned_busin"),
        ("hispanic_american_owned_bu", "hispanic_american_owned_bu"),
        ("native_american_owned_busi", "native_american_owned_busi"),
        ("subcontinent_asian_asian_i", "subcontinent_asian_asian_i"),
        ("other_minority_owned_busin", "other_minority_owned_busin"),
        ("for_profit_organization", "for_profit_organization"),
        ("nonprofit_organization", "nonprofit_organization"),
        ("other_not_for_profit_organ", "other_not_for_profit_organ"),
        ("us_local_government", "us_local_government"),
        ("referenced_idv_modificatio", "referenced_idv_modificatio"),
        ("undefinitized_action", "undefinitized_action"),
        ("undefinitized_action_desc", "undefinitized_action_desc"),
        ("domestic_or_foreign_entity", "domestic_or_foreign_entity"),
        ("domestic_or_foreign_e_desc", "domestic_or_foreign_e_desc"),
        ("pulled_from", "pulled_from"),
        ("last_modified", "last_modified"),
        ("annual_revenue", "annual_revenue"),
        ("division_name", "division_name"),
        ("division_number_or_office", "division_number_or_office"),
        ("number_of_employees", "number_of_employees"),
        ("vendor_alternate_name", "vendor_alternate_name"),
        ("vendor_alternate_site_code", "vendor_alternate_site_code"),
        ("vendor_enabled", "vendor_enabled"),
        ("vendor_legal_org_name", "vendor_legal_org_name"),
        ("vendor_location_disabled_f", "vendor_location_disabled_f"),
        ("vendor_site_code", "vendor_site_code"),
        ("initial_report_date", "initial_report_date"),
        ("base_and_all_options_value", "base_and_all_options_value"),
        ("base_exercised_options_val", "base_exercised_options_val"),
        ("total_obligated_amount", "total_obligated_amount"),
        ("place_of_perform_country_n", "place_of_perform_country_n"),
        ("place_of_perform_state_nam", "place_of_perform_state_nam"),
        ("referenced_idv_agency_name", "referenced_idv_agency_name"),
        ("award_or_idv_flag", "award_or_idv_flag"),
        ("legal_entity_county_code", "legal_entity_county_code"),
        ("legal_entity_county_name", "legal_entity_county_name"),
        ("legal_entity_zip5", "legal_entity_zip5"),
        ("legal_entity_zip_last4", "legal_entity_zip_last4"),
        ("place_of_perform_county_co", "place_of_perform_county_co"),
        ("place_of_performance_zip5", "place_of_performance_zip5"),
        ("place_of_perform_zip_last4", "place_of_perform_zip_last4"),
        ("cage_code", "cage_code"),
        ("inherently_government_func", "inherently_government_func"),
        ("organizational_type", "organizational_type"),
        ("inherently_government_desc", "inherently_government_desc"),
        ("unique_award_key", "unique_award_key"),
        ("high_comp_officer1_amount", "officer_1_amount"),
        ("high_comp_officer1_full_na", "officer_1_name"),
        ("high_comp_officer2_amount", "officer_2_amount"),
        ("high_comp_officer2_full_na", "officer_2_name"),
        ("high_comp_officer3_amount", "officer_3_amount"),
        ("high_comp_officer3_full_na", "officer_3_name"),
        ("high_comp_officer4_amount", "officer_4_amount"),
        ("high_comp_officer4_full_na", "officer_4_name"),
        ("high_comp_officer5_amount", "officer_5_amount"),
        ("high_comp_officer5_full_na", "officer_5_name"),
    ]
)


PUBLISHED_AWARD_FINANCIAL_ASSISTANCE = """
created_at,
updated_at,
action_date::date::text,
UPPER(action_type) AS action_type,
UPPER(assistance_type) AS assistance_type,
UPPER(award_description) AS award_description,
UPPER(awardee_or_recipient_legal) AS awardee_or_recipient_legal,
UPPER(awardee_or_recipient_uniqu) AS awardee_or_recipient_uniqu,
UPPER(awarding_agency_code) AS awarding_agency_code,
UPPER(awarding_office_code) AS awarding_office_code,
UPPER(awarding_sub_tier_agency_c) AS awarding_sub_tier_agency_c,
UPPER(award_modification_amendme) AS award_modification_amendme,
UPPER(business_funds_indicator) AS business_funds_indicator,
UPPER(business_types) AS business_types,
UPPER(cfda_number) AS cfda_number,
UPPER(correction_delete_indicatr) AS correction_delete_indicatr,
face_value_loan_guarantee,
UPPER(fain) AS fain,
federal_action_obligation,
UPPER(fiscal_year_and_quarter_co) AS fiscal_year_and_quarter_co,
UPPER(funding_agency_code) AS funding_agency_code,
UPPER(funding_office_code) AS funding_office_code,
UPPER(funding_sub_tier_agency_co) AS funding_sub_tier_agency_co,
UPPER(legal_entity_address_line1) AS legal_entity_address_line1,
UPPER(legal_entity_address_line2) AS legal_entity_address_line2,
UPPER(legal_entity_address_line3) AS legal_entity_address_line3,
UPPER(legal_entity_country_code) AS legal_entity_country_code,
UPPER(legal_entity_foreign_city) AS legal_entity_foreign_city,
UPPER(legal_entity_foreign_posta) AS legal_entity_foreign_posta,
UPPER(legal_entity_foreign_provi) AS legal_entity_foreign_provi,
UPPER(legal_entity_zip5) AS legal_entity_zip5,
UPPER(legal_entity_zip_last4) AS legal_entity_zip_last4,
non_federal_funding_amount,
original_loan_subsidy_cost,
UPPER(period_of_performance_curr) AS period_of_performance_curr,
UPPER(period_of_performance_star) AS period_of_performance_star,
UPPER(place_of_performance_code) AS place_of_performance_code,
UPPER(place_of_performance_congr) AS place_of_performance_congr,
UPPER(place_of_perform_country_c) AS place_of_perform_country_c,
UPPER(place_of_performance_forei) AS place_of_performance_forei,
UPPER(place_of_performance_zip4a) AS place_of_performance_zip4a,
record_type,
UPPER(sai_number) AS sai_number,
UPPER(uri) AS uri,
UPPER(legal_entity_congressional) AS legal_entity_congressional,
total_funding_amount,
UPPER(cfda_title) AS cfda_title,
UPPER(awarding_agency_name) AS awarding_agency_name,
UPPER(awarding_sub_tier_agency_n) AS awarding_sub_tier_agency_n,
UPPER(funding_agency_name) AS funding_agency_name,
UPPER(funding_sub_tier_agency_na) AS funding_sub_tier_agency_na,
is_historical,
UPPER(place_of_perform_county_na) AS place_of_perform_county_na,
UPPER(place_of_perform_state_nam) AS place_of_perform_state_nam,
UPPER(place_of_performance_city) AS place_of_performance_city,
UPPER(legal_entity_city_name) AS legal_entity_city_name,
UPPER(legal_entity_county_code) AS legal_entity_county_code,
UPPER(legal_entity_county_name) AS legal_entity_county_name,
UPPER(legal_entity_state_code) AS legal_entity_state_code,
UPPER(legal_entity_state_name) AS legal_entity_state_name,
modified_at,
UPPER(afa_generated_unique) AS afa_generated_unique,
is_active,
UPPER(awarding_office_name) AS awarding_office_name,
UPPER(funding_office_name) AS funding_office_name,
UPPER(legal_entity_city_code) AS legal_entity_city_code,
UPPER(legal_entity_foreign_descr) AS legal_entity_foreign_descr,
UPPER(legal_entity_country_name) AS legal_entity_country_name,
UPPER(place_of_perform_country_n) AS place_of_perform_country_n,
UPPER(place_of_perform_county_co) AS place_of_perform_county_co,
submission_id,
UPPER(place_of_perfor_state_code) AS place_of_perfor_state_code,
UPPER(place_of_performance_zip5) AS place_of_performance_zip5,
UPPER(place_of_perform_zip_last4) AS place_of_perform_zip_last4,
UPPER(action_type_description) AS action_type_description,
UPPER(assistance_type_desc) AS assistance_type_desc,
UPPER(business_funds_ind_desc) AS business_funds_ind_desc,
UPPER(business_types_desc) AS business_types_desc,
UPPER(correction_delete_ind_desc) AS correction_delete_ind_desc,
UPPER(record_type_description) AS record_type_description,
UPPER(ultimate_parent_legal_enti) AS ultimate_parent_legal_enti,
UPPER(ultimate_parent_unique_ide) AS ultimate_parent_unique_ide,
UPPER(unique_award_key) AS unique_award_key,
high_comp_officer1_amount,
UPPER(high_comp_officer1_full_na) AS high_comp_officer1_full_na,
high_comp_officer2_amount,
UPPER(high_comp_officer2_full_na) AS high_comp_officer2_full_na,
high_comp_officer3_amount,
UPPER(high_comp_officer3_full_na) AS high_comp_officer3_full_na,
high_comp_officer4_amount,
UPPER(high_comp_officer4_full_na) AS high_comp_officer4_full_na,
high_comp_officer5_amount,
UPPER(high_comp_officer5_full_na) AS high_comp_officer5_full_na
"""


TRANSACTION_FABS = """
created_at::TIMESTAMP WITHOUT TIME ZONE,
updated_at::TIMESTAMP WITHOUT TIME ZONE,
action_date::date::text,
action_type,
assistance_type,
award_description,
awardee_or_recipient_legal,
awardee_or_recipient_uniqu,
awarding_agency_code,
awarding_office_code,
awarding_sub_tier_agency_c,
award_modification_amendme,
business_funds_indicator,
business_types,
cfda_number,
correction_delete_indicatr,
face_value_loan_guarantee,
fain,
federal_action_obligation,
fiscal_year_and_quarter_co,
funding_agency_code,
funding_office_code,
funding_sub_tier_agency_co,
legal_entity_address_line1,
legal_entity_address_line2,
legal_entity_address_line3,
legal_entity_country_code,
legal_entity_foreign_city,
legal_entity_foreign_posta,
legal_entity_foreign_provi,
legal_entity_zip5,
legal_entity_zip_last4,
non_federal_funding_amount,
original_loan_subsidy_cost,
period_of_performance_curr,
period_of_performance_star,
place_of_performance_code,
place_of_performance_congr,
place_of_perform_country_c,
place_of_performance_forei,
place_of_performance_zip4a,
record_type,
sai_number,
uri,
legal_entity_congressional,
total_funding_amount,
cfda_title,
awarding_agency_name,
awarding_sub_tier_agency_n,
funding_agency_name,
funding_sub_tier_agency_na,
is_historical,
place_of_perform_county_na,
place_of_perform_state_nam,
place_of_performance_city,
legal_entity_city_name,
legal_entity_county_code,
legal_entity_county_name,
legal_entity_state_code,
legal_entity_state_name,
modified_at::TIMESTAMP WITHOUT TIME ZONE,
afa_generated_unique,
is_active,
awarding_office_name,
funding_office_name,
legal_entity_city_code,
legal_entity_foreign_descr,
legal_entity_country_name,
place_of_perform_country_n,
place_of_perform_county_co,
submission_id,
place_of_perfor_state_code,
place_of_performance_zip5,
place_of_perform_zip_last4,
action_type_description,
assistance_type_desc,
business_funds_ind_desc,
business_types_desc,
correction_delete_ind_desc,
record_type_description,
ultimate_parent_legal_enti,
ultimate_parent_unique_ide,
unique_award_key,
officer_1_amount::text,
officer_1_name,
officer_2_amount::text,
officer_2_name,
officer_3_amount::text,
officer_3_name,
officer_4_amount::text,
officer_4_name,
officer_5_amount::text,
officer_5_name
"""

DETATCHED_AWARD_PROCURMENT = """
created_at::TIMESTAMP WITHOUT TIME ZONE,
updated_at::TIMESTAMP WITHOUT TIME ZONE,
UPPER(piid) AS piid,
UPPER(detached_award_proc_unique) AS detached_award_proc_unique,
UPPER(agency_id) AS agency_id,
UPPER(awarding_sub_tier_agency_c) AS awarding_sub_tier_agency_c,
UPPER(awarding_sub_tier_agency_n) AS awarding_sub_tier_agency_n,
UPPER(awarding_agency_code) AS awarding_agency_code,
UPPER(awarding_agency_name) AS awarding_agency_name,
UPPER(parent_award_id) AS parent_award_id,
UPPER(award_modification_amendme) AS award_modification_amendme,
UPPER(type_of_contract_pricing) AS type_of_contract_pricing,
UPPER(type_of_contract_pric_desc) AS type_of_contract_pric_desc,
UPPER(contract_award_type) AS contract_award_type,
UPPER(contract_award_type_desc) AS contract_award_type_desc,
UPPER(naics) AS naics,
UPPER(naics_description) AS naics_description,
UPPER(awardee_or_recipient_uniqu) AS awardee_or_recipient_uniqu,
UPPER(ultimate_parent_legal_enti) AS ultimate_parent_legal_enti,
UPPER(ultimate_parent_unique_ide) AS ultimate_parent_unique_ide,
UPPER(award_description) AS award_description,
UPPER(place_of_performance_zip4a) AS place_of_performance_zip4a,
UPPER(place_of_perform_city_name) AS place_of_perform_city_name,
UPPER(place_of_perform_county_na) AS place_of_perform_county_na,
UPPER(place_of_performance_congr) AS place_of_performance_congr,
UPPER(awardee_or_recipient_legal) AS awardee_or_recipient_legal,
UPPER(legal_entity_city_name) AS legal_entity_city_name,
UPPER(legal_entity_state_code) AS legal_entity_state_code,
UPPER(legal_entity_state_descrip) AS legal_entity_state_descrip,
UPPER(legal_entity_zip4) AS legal_entity_zip4,
UPPER(legal_entity_congressional) AS legal_entity_congressional,
UPPER(legal_entity_address_line1) AS legal_entity_address_line1,
UPPER(legal_entity_address_line2) AS legal_entity_address_line2,
UPPER(legal_entity_address_line3) AS legal_entity_address_line3,
UPPER(legal_entity_country_code) AS legal_entity_country_code,
UPPER(legal_entity_country_name) AS legal_entity_country_name,
UPPER(period_of_performance_star) AS period_of_performance_star,
UPPER(period_of_performance_curr) AS period_of_performance_curr,
UPPER(period_of_perf_potential_e) AS period_of_perf_potential_e,
UPPER(ordering_period_end_date) AS ordering_period_end_date,
UPPER(action_date) AS action_date,
UPPER(action_type) AS action_type,
UPPER(action_type_description) AS action_type_description,
federal_action_obligation AS federal_action_obligation,
UPPER(current_total_value_award) AS current_total_value_award,
UPPER(potential_total_value_awar) AS potential_total_value_awar,
UPPER(funding_sub_tier_agency_co) AS funding_sub_tier_agency_co,
UPPER(funding_sub_tier_agency_na) AS funding_sub_tier_agency_na,
UPPER(funding_office_code) AS funding_office_code,
UPPER(funding_office_name) AS funding_office_name,
UPPER(awarding_office_code) AS awarding_office_code,
UPPER(awarding_office_name) AS awarding_office_name,
UPPER(referenced_idv_agency_iden) AS referenced_idv_agency_iden,
UPPER(referenced_idv_agency_desc) AS referenced_idv_agency_desc,
UPPER(funding_agency_code) AS funding_agency_code,
UPPER(funding_agency_name) AS funding_agency_name,
UPPER(place_of_performance_locat) AS place_of_performance_locat,
UPPER(place_of_performance_state) AS place_of_performance_state,
UPPER(place_of_perfor_state_desc) AS place_of_perfor_state_desc,
UPPER(place_of_perform_country_c) AS place_of_perform_country_c,
UPPER(place_of_perf_country_desc) AS place_of_perf_country_desc,
UPPER(idv_type) AS idv_type,
UPPER(idv_type_description) AS idv_type_description,
UPPER(referenced_idv_type) AS referenced_idv_type,
UPPER(referenced_idv_type_desc) AS referenced_idv_type_desc,
UPPER(vendor_doing_as_business_n) AS vendor_doing_as_business_n,
UPPER(vendor_phone_number) AS vendor_phone_number,
UPPER(vendor_fax_number) AS vendor_fax_number,
UPPER(multiple_or_single_award_i) AS multiple_or_single_award_i,
UPPER(multiple_or_single_aw_desc) AS multiple_or_single_aw_desc,
UPPER(referenced_mult_or_single) AS referenced_mult_or_single,
UPPER(referenced_mult_or_si_desc) AS referenced_mult_or_si_desc,
UPPER(type_of_idc) AS type_of_idc,
UPPER(type_of_idc_description) AS type_of_idc_description,
UPPER(a_76_fair_act_action) AS a_76_fair_act_action,
UPPER(a_76_fair_act_action_desc) AS a_76_fair_act_action_desc,
UPPER(dod_claimant_program_code) AS dod_claimant_program_code,
UPPER(dod_claimant_prog_cod_desc) AS dod_claimant_prog_cod_desc,
UPPER(clinger_cohen_act_planning) AS clinger_cohen_act_planning,
UPPER(clinger_cohen_act_pla_desc) AS clinger_cohen_act_pla_desc,
UPPER(commercial_item_acquisitio) AS commercial_item_acquisitio,
UPPER(commercial_item_acqui_desc) AS commercial_item_acqui_desc,
UPPER(commercial_item_test_progr) AS commercial_item_test_progr,
UPPER(commercial_item_test_desc) AS commercial_item_test_desc,
UPPER(consolidated_contract) AS consolidated_contract,
UPPER(consolidated_contract_desc) AS consolidated_contract_desc,
UPPER(contingency_humanitarian_o) AS contingency_humanitarian_o,
UPPER(contingency_humanitar_desc) AS contingency_humanitar_desc,
UPPER(contract_bundling) AS contract_bundling,
UPPER(contract_bundling_descrip) AS contract_bundling_descrip,
UPPER(contract_financing) AS contract_financing,
UPPER(contract_financing_descrip) AS contract_financing_descrip,
UPPER(contracting_officers_deter) AS contracting_officers_deter,
UPPER(contracting_officers_desc) AS contracting_officers_desc,
UPPER(cost_accounting_standards) AS cost_accounting_standards,
UPPER(cost_accounting_stand_desc) AS cost_accounting_stand_desc,
UPPER(cost_or_pricing_data) AS cost_or_pricing_data,
UPPER(cost_or_pricing_data_desc) AS cost_or_pricing_data_desc,
UPPER(country_of_product_or_serv) AS country_of_product_or_serv,
UPPER(country_of_product_or_desc) AS country_of_product_or_desc,
UPPER(construction_wage_rate_req) AS construction_wage_rate_req,
UPPER(construction_wage_rat_desc) AS construction_wage_rat_desc,
UPPER(evaluated_preference) AS evaluated_preference,
UPPER(evaluated_preference_desc) AS evaluated_preference_desc,
UPPER(extent_competed) AS extent_competed,
UPPER(extent_compete_description) AS extent_compete_description,
UPPER(fed_biz_opps) AS fed_biz_opps,
UPPER(fed_biz_opps_description) AS fed_biz_opps_description,
UPPER(foreign_funding) AS foreign_funding,
UPPER(foreign_funding_desc) AS foreign_funding_desc,
UPPER(government_furnished_prope) AS government_furnished_prope,
UPPER(government_furnished_desc) AS government_furnished_desc,
UPPER(information_technology_com) AS information_technology_com,
UPPER(information_technolog_desc) AS information_technolog_desc,
UPPER(interagency_contracting_au) AS interagency_contracting_au,
UPPER(interagency_contract_desc) AS interagency_contract_desc,
UPPER(local_area_set_aside) AS local_area_set_aside,
UPPER(local_area_set_aside_desc) AS local_area_set_aside_desc,
UPPER(major_program) AS major_program,
UPPER(purchase_card_as_payment_m) AS purchase_card_as_payment_m,
UPPER(purchase_card_as_paym_desc) AS purchase_card_as_paym_desc,
UPPER(multi_year_contract) AS multi_year_contract,
UPPER(multi_year_contract_desc) AS multi_year_contract_desc,
UPPER(national_interest_action) AS national_interest_action,
UPPER(national_interest_desc) AS national_interest_desc,
UPPER(number_of_actions) AS number_of_actions,
UPPER(number_of_offers_received) AS number_of_offers_received,
UPPER(other_statutory_authority) AS other_statutory_authority,
UPPER(performance_based_service) AS performance_based_service,
UPPER(performance_based_se_desc) AS performance_based_se_desc,
UPPER(place_of_manufacture) AS place_of_manufacture,
UPPER(place_of_manufacture_desc) AS place_of_manufacture_desc,
UPPER(price_evaluation_adjustmen) AS price_evaluation_adjustmen,
UPPER(product_or_service_code) AS product_or_service_code,
UPPER(product_or_service_co_desc) AS product_or_service_co_desc,
UPPER(program_acronym) AS program_acronym,
UPPER(other_than_full_and_open_c) AS other_than_full_and_open_c,
UPPER(other_than_full_and_o_desc) AS other_than_full_and_o_desc,
UPPER(recovered_materials_sustai) AS recovered_materials_sustai,
UPPER(recovered_materials_s_desc) AS recovered_materials_s_desc,
UPPER(research) AS research,
UPPER(research_description) AS research_description,
UPPER(sea_transportation) AS sea_transportation,
UPPER(sea_transportation_desc) AS sea_transportation_desc,
UPPER(labor_standards) AS labor_standards,
UPPER(labor_standards_descrip) AS labor_standards_descrip,
UPPER(small_business_competitive) AS small_business_competitive,
UPPER(solicitation_identifier) AS solicitation_identifier,
UPPER(solicitation_procedures) AS solicitation_procedures,
UPPER(solicitation_procedur_desc) AS solicitation_procedur_desc,
UPPER(fair_opportunity_limited_s) AS fair_opportunity_limited_s,
UPPER(fair_opportunity_limi_desc) AS fair_opportunity_limi_desc,
UPPER(subcontracting_plan) AS subcontracting_plan,
UPPER(subcontracting_plan_desc) AS subcontracting_plan_desc,
UPPER(program_system_or_equipmen) AS program_system_or_equipmen,
UPPER(program_system_or_equ_desc) AS program_system_or_equ_desc,
UPPER(type_set_aside) AS type_set_aside,
UPPER(type_set_aside_description) AS type_set_aside_description,
UPPER(epa_designated_product) AS epa_designated_product,
UPPER(epa_designated_produc_desc) AS epa_designated_produc_desc,
UPPER(materials_supplies_article) AS materials_supplies_article,
UPPER(materials_supplies_descrip) AS materials_supplies_descrip,
UPPER(transaction_number) AS transaction_number,
UPPER(sam_exception) AS sam_exception,
UPPER(sam_exception_description) AS sam_exception_description,
UPPER(city_local_government) AS city_local_government,
UPPER(county_local_government) AS county_local_government,
UPPER(inter_municipal_local_gove) AS inter_municipal_local_gove,
UPPER(local_government_owned) AS local_government_owned,
UPPER(municipality_local_governm) AS municipality_local_governm,
UPPER(school_district_local_gove) AS school_district_local_gove,
UPPER(township_local_government) AS township_local_government,
UPPER(us_state_government) AS us_state_government,
UPPER(us_federal_government) AS us_federal_government,
federal_agency::boolean AS federal_agency,
UPPER(federally_funded_research) AS federally_funded_research,
UPPER(us_tribal_government) AS us_tribal_government,
UPPER(foreign_government) AS foreign_government,
UPPER(community_developed_corpor) AS community_developed_corpor,
UPPER(labor_surplus_area_firm) AS labor_surplus_area_firm,
UPPER(corporate_entity_not_tax_e) AS corporate_entity_not_tax_e,
UPPER(corporate_entity_tax_exemp) AS corporate_entity_tax_exemp,
UPPER(partnership_or_limited_lia) AS partnership_or_limited_lia,
UPPER(sole_proprietorship) AS sole_proprietorship,
UPPER(small_agricultural_coopera) AS small_agricultural_coopera,
UPPER(international_organization) AS international_organization,
UPPER(us_government_entity) AS us_government_entity,
emerging_small_business::boolean AS emerging_small_business,
UPPER(c8a_program_participant) AS c8a_program_participant,
UPPER(sba_certified_8_a_joint_ve) AS sba_certified_8_a_joint_ve,
UPPER(dot_certified_disadvantage) AS dot_certified_disadvantage,
UPPER(self_certified_small_disad) AS self_certified_small_disad,
UPPER(historically_underutilized) AS historically_underutilized,
UPPER(small_disadvantaged_busine) AS small_disadvantaged_busine,
UPPER(the_ability_one_program) AS the_ability_one_program,
UPPER(historically_black_college) AS historically_black_college,
UPPER(c1862_land_grant_college) AS c1862_land_grant_college,
UPPER(c1890_land_grant_college) AS c1890_land_grant_college,
UPPER(c1994_land_grant_college) AS c1994_land_grant_college,
UPPER(minority_institution) AS minority_institution,
UPPER(private_university_or_coll) AS private_university_or_coll,
UPPER(school_of_forestry) AS school_of_forestry,
state_controlled_instituti::boolean AS state_controlled_instituti,
UPPER(tribal_college) AS tribal_college,
UPPER(veterinary_college) AS veterinary_college,
UPPER(educational_institution) AS educational_institution,
UPPER(alaskan_native_servicing_i) AS alaskan_native_servicing_i,
UPPER(community_development_corp) AS community_development_corp,
UPPER(native_hawaiian_servicing) AS native_hawaiian_servicing,
UPPER(domestic_shelter) AS domestic_shelter,
UPPER(manufacturer_of_goods) AS manufacturer_of_goods,
UPPER(hospital_flag) AS hospital_flag,
UPPER(veterinary_hospital) AS veterinary_hospital,
UPPER(hispanic_servicing_institu) AS hispanic_servicing_institu,
UPPER(foundation) AS foundation,
UPPER(woman_owned_business) AS woman_owned_business,
UPPER(minority_owned_business) AS minority_owned_business,
UPPER(women_owned_small_business) AS women_owned_small_business,
UPPER(economically_disadvantaged) AS economically_disadvantaged,
UPPER(joint_venture_women_owned) AS joint_venture_women_owned,
UPPER(joint_venture_economically) AS joint_venture_economically,
UPPER(veteran_owned_business) AS veteran_owned_business,
UPPER(service_disabled_veteran_o) AS service_disabled_veteran_o,
UPPER(contracts) AS contracts,
UPPER(grants) AS grants,
UPPER(receives_contracts_and_gra) AS receives_contracts_and_gra,
UPPER(airport_authority) AS airport_authority,
UPPER(council_of_governments) AS council_of_governments,
UPPER(housing_authorities_public) AS housing_authorities_public,
UPPER(interstate_entity) AS interstate_entity,
UPPER(planning_commission) AS planning_commission,
UPPER(port_authority) AS port_authority,
UPPER(transit_authority) AS transit_authority,
UPPER(subchapter_s_corporation) AS subchapter_s_corporation,
UPPER(limited_liability_corporat) AS limited_liability_corporat,
UPPER(foreign_owned_and_located) AS foreign_owned_and_located,
UPPER(american_indian_owned_busi) AS american_indian_owned_busi,
UPPER(alaskan_native_owned_corpo) AS alaskan_native_owned_corpo,
UPPER(indian_tribe_federally_rec) AS indian_tribe_federally_rec,
UPPER(native_hawaiian_owned_busi) AS native_hawaiian_owned_busi,
UPPER(tribally_owned_business) AS tribally_owned_business,
UPPER(asian_pacific_american_own) AS asian_pacific_american_own,
UPPER(black_american_owned_busin) AS black_american_owned_busin,
UPPER(hispanic_american_owned_bu) AS hispanic_american_owned_bu,
UPPER(native_american_owned_busi) AS native_american_owned_busi,
UPPER(subcontinent_asian_asian_i) AS subcontinent_asian_asian_i,
UPPER(other_minority_owned_busin) AS other_minority_owned_busin,
UPPER(for_profit_organization) AS for_profit_organization,
UPPER(nonprofit_organization) AS nonprofit_organization,
UPPER(other_not_for_profit_organ) AS other_not_for_profit_organ,
UPPER(us_local_government) AS us_local_government,
UPPER(referenced_idv_modificatio) AS referenced_idv_modificatio,
UPPER(undefinitized_action) AS undefinitized_action,
UPPER(undefinitized_action_desc) AS undefinitized_action_desc,
UPPER(domestic_or_foreign_entity) AS domestic_or_foreign_entity,
UPPER(domestic_or_foreign_e_desc) AS domestic_or_foreign_e_desc,
UPPER(pulled_from) AS pulled_from,
UPPER(last_modified) AS last_modified,
UPPER(annual_revenue) AS annual_revenue,
UPPER(division_name) AS division_name,
UPPER(division_number_or_office) AS division_number_or_office,
UPPER(number_of_employees) AS number_of_employees,
UPPER(vendor_alternate_name) AS vendor_alternate_name,
UPPER(vendor_alternate_site_code) AS vendor_alternate_site_code,
UPPER(vendor_enabled) AS vendor_enabled,
UPPER(vendor_legal_org_name) AS vendor_legal_org_name,
UPPER(vendor_location_disabled_f) AS vendor_location_disabled_f,
UPPER(vendor_site_code) AS vendor_site_code,
UPPER(initial_report_date) AS initial_report_date,
UPPER(base_and_all_options_value) AS base_and_all_options_value,
UPPER(base_exercised_options_val) AS base_exercised_options_val,
UPPER(total_obligated_amount) AS total_obligated_amount,
UPPER(place_of_perform_country_n) AS place_of_perform_country_n,
UPPER(place_of_perform_state_nam) AS place_of_perform_state_nam,
UPPER(referenced_idv_agency_name) AS referenced_idv_agency_name,
UPPER(award_or_idv_flag) AS award_or_idv_flag,
UPPER(legal_entity_county_code) AS legal_entity_county_code,
UPPER(legal_entity_county_name) AS legal_entity_county_name,
UPPER(legal_entity_zip5) AS legal_entity_zip5,
UPPER(legal_entity_zip_last4) AS legal_entity_zip_last4,
UPPER(place_of_perform_county_co) AS place_of_perform_county_co,
UPPER(place_of_performance_zip5) AS place_of_performance_zip5,
UPPER(place_of_perform_zip_last4) AS place_of_perform_zip_last4,
UPPER(cage_code) AS cage_code,
UPPER(inherently_government_func) AS inherently_government_func,
UPPER(organizational_type) AS organizational_type,
UPPER(inherently_government_desc) AS inherently_government_desc,
UPPER(unique_award_key) AS unique_award_key,
high_comp_officer1_amount,
UPPER(high_comp_officer1_full_na) AS high_comp_officer1_full_na,
high_comp_officer2_amount,
UPPER(high_comp_officer2_full_na) AS high_comp_officer2_full_na,
high_comp_officer3_amount,
UPPER(high_comp_officer3_full_na) AS high_comp_officer3_full_na,
high_comp_officer4_amount,
UPPER(high_comp_officer4_full_na) AS high_comp_officer4_full_na,
high_comp_officer5_amount,
UPPER(high_comp_officer5_full_na) AS high_comp_officer5_full_na
"""


TRANSACTION_FPDS = """
created_at::TIMESTAMP WITHOUT TIME ZONE,
updated_at::TIMESTAMP WITHOUT TIME ZONE,
piid,
detached_award_proc_unique,
agency_id,
awarding_sub_tier_agency_c,
awarding_sub_tier_agency_n,
awarding_agency_code,
awarding_agency_name,
parent_award_id,
award_modification_amendme,
type_of_contract_pricing,
type_of_contract_pric_desc,
contract_award_type,
contract_award_type_desc,
naics,
naics_description,
awardee_or_recipient_uniqu,
ultimate_parent_legal_enti,
ultimate_parent_unique_ide,
award_description,
place_of_performance_zip4a,
place_of_perform_city_name,
place_of_perform_county_na,
place_of_performance_congr,
awardee_or_recipient_legal,
legal_entity_city_name,
legal_entity_state_code,
legal_entity_state_descrip,
legal_entity_zip4,
legal_entity_congressional,
legal_entity_address_line1,
legal_entity_address_line2,
legal_entity_address_line3,
legal_entity_country_code,
legal_entity_country_name,
period_of_performance_star,
period_of_performance_curr,
period_of_perf_potential_e,
ordering_period_end_date,
action_date,
action_type,
action_type_description,
federal_action_obligation,
current_total_value_award,
potential_total_value_awar,
funding_sub_tier_agency_co,
funding_sub_tier_agency_na,
funding_office_code,
funding_office_name,
awarding_office_code,
awarding_office_name,
referenced_idv_agency_iden,
referenced_idv_agency_desc,
funding_agency_code,
funding_agency_name,
place_of_performance_locat,
place_of_performance_state,
place_of_perfor_state_desc,
place_of_perform_country_c,
place_of_perf_country_desc,
idv_type,
idv_type_description,
referenced_idv_type,
referenced_idv_type_desc,
vendor_doing_as_business_n,
vendor_phone_number,
vendor_fax_number,
multiple_or_single_award_i,
multiple_or_single_aw_desc,
referenced_mult_or_single,
referenced_mult_or_si_desc,
type_of_idc,
type_of_idc_description,
a_76_fair_act_action,
a_76_fair_act_action_desc,
dod_claimant_program_code,
dod_claimant_prog_cod_desc,
clinger_cohen_act_planning,
clinger_cohen_act_pla_desc,
commercial_item_acquisitio,
commercial_item_acqui_desc,
commercial_item_test_progr,
commercial_item_test_desc,
consolidated_contract,
consolidated_contract_desc,
contingency_humanitarian_o,
contingency_humanitar_desc,
contract_bundling,
contract_bundling_descrip,
contract_financing,
contract_financing_descrip,
contracting_officers_deter,
contracting_officers_desc,
cost_accounting_standards,
cost_accounting_stand_desc,
cost_or_pricing_data,
cost_or_pricing_data_desc,
country_of_product_or_serv,
country_of_product_or_desc,
construction_wage_rate_req,
construction_wage_rat_desc,
evaluated_preference,
evaluated_preference_desc,
extent_competed,
extent_compete_description,
fed_biz_opps,
fed_biz_opps_description,
foreign_funding,
foreign_funding_desc,
government_furnished_prope,
government_furnished_desc,
information_technology_com,
information_technolog_desc,
interagency_contracting_au,
interagency_contract_desc,
local_area_set_aside,
local_area_set_aside_desc,
major_program,
purchase_card_as_payment_m,
purchase_card_as_paym_desc,
multi_year_contract,
multi_year_contract_desc,
national_interest_action,
national_interest_desc,
number_of_actions,
number_of_offers_received,
other_statutory_authority,
performance_based_service,
performance_based_se_desc,
place_of_manufacture,
place_of_manufacture_desc,
price_evaluation_adjustmen,
product_or_service_code,
product_or_service_co_desc,
program_acronym,
other_than_full_and_open_c,
other_than_full_and_o_desc,
recovered_materials_sustai,
recovered_materials_s_desc,
research,
research_description,
sea_transportation,
sea_transportation_desc,
labor_standards,
labor_standards_descrip,
small_business_competitive::text,
solicitation_identifier,
solicitation_procedures,
solicitation_procedur_desc,
fair_opportunity_limited_s,
fair_opportunity_limi_desc,
subcontracting_plan,
subcontracting_plan_desc,
program_system_or_equipmen,
program_system_or_equ_desc,
type_set_aside,
type_set_aside_description,
epa_designated_product,
epa_designated_produc_desc,
materials_supplies_article,
materials_supplies_descrip,
transaction_number,
sam_exception,
sam_exception_description,
city_local_government::text,
county_local_government::text,
inter_municipal_local_gove::text,
local_government_owned::text,
municipality_local_governm::text,
school_district_local_gove::text,
township_local_government::text,
us_state_government::text,
us_federal_government::text,
federal_agency::text,
federally_funded_research::text,
us_tribal_government::text,
foreign_government::text,
community_developed_corpor::text,
labor_surplus_area_firm::text,
corporate_entity_not_tax_e::text,
corporate_entity_tax_exemp::text,
partnership_or_limited_lia::text,
sole_proprietorship::text,
small_agricultural_coopera::text,
international_organization::text,
us_government_entity::text,
emerging_small_business::text,
c8a_program_participant::text,
sba_certified_8_a_joint_ve::text,
dot_certified_disadvantage::text,
self_certified_small_disad::text,
historically_underutilized::text,
small_disadvantaged_busine::text,
the_ability_one_program::text,
historically_black_college::text,
c1862_land_grant_college::text,
c1890_land_grant_college::text,
c1994_land_grant_college::text,
minority_institution::text,
private_university_or_coll::text,
school_of_forestry::text,
state_controlled_instituti::text,
tribal_college::text,
veterinary_college::text,
educational_institution::text,
alaskan_native_servicing_i::text,
community_development_corp::text,
native_hawaiian_servicing::text,
domestic_shelter::text,
manufacturer_of_goods::text,
hospital_flag::text,
veterinary_hospital::text,
hispanic_servicing_institu::text,
foundation::text,
woman_owned_business::text,
minority_owned_business::text,
women_owned_small_business::text,
economically_disadvantaged::text,
joint_venture_women_owned::text,
joint_venture_economically::text,
veteran_owned_business::text,
service_disabled_veteran_o::text,
contracts::text,
grants::text,
receives_contracts_and_gra::text,
airport_authority::text,
council_of_governments::text,
housing_authorities_public::text,
interstate_entity::text,
planning_commission::text,
port_authority::text,
transit_authority::text,
subchapter_s_corporation::text,
limited_liability_corporat::text,
foreign_owned_and_located::text,
american_indian_owned_busi::text,
alaskan_native_owned_corpo::text,
indian_tribe_federally_rec::text,
native_hawaiian_owned_busi::text,
tribally_owned_business::text,
asian_pacific_american_own::text,
black_american_owned_busin::text,
hispanic_american_owned_bu::text,
native_american_owned_busi::text,
subcontinent_asian_asian_i::text,
other_minority_owned_busin::text,
for_profit_organization::text,
nonprofit_organization::text,
other_not_for_profit_organ::text,
us_local_government::text,
referenced_idv_modificatio,
undefinitized_action,
undefinitized_action_desc,
domestic_or_foreign_entity,
domestic_or_foreign_e_desc,
pulled_from,
last_modified,
annual_revenue,
division_name,
division_number_or_office,
number_of_employees,
vendor_alternate_name,
vendor_alternate_site_code,
vendor_enabled,
vendor_legal_org_name,
vendor_location_disabled_f,
vendor_site_code,
initial_report_date,
base_and_all_options_value,
base_exercised_options_val,
total_obligated_amount,
place_of_perform_country_n,
place_of_perform_state_nam,
referenced_idv_agency_name,
award_or_idv_flag,
legal_entity_county_code,
legal_entity_county_name,
legal_entity_zip5,
legal_entity_zip_last4,
place_of_perform_county_co,
place_of_performance_zip5,
place_of_perform_zip_last4,
cage_code,
inherently_government_func,
organizational_type,
inherently_government_desc,
unique_award_key,
officer_1_amount::text,
officer_1_name,
officer_2_amount::text,
officer_2_name,
officer_3_amount::text,
officer_3_name,
officer_4_amount::text,
officer_4_name,
officer_5_amount::text,
officer_5_name
"""
